<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Quantum.Plugin.Abstraction</AssemblyName>
    <PackageId>Quantum.Plugin.Abstraction</PackageId>
    <Description>The stable .NET plugin ABI for Quantum.</Description>
    <Version>0.1.0-alpha.1</Version>
    <Authors>Quantum contributors</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/XmmShp/Quantum</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="NOF.Abstraction" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
